import Foundation

/// Maps merchant names to expense categories using keyword heuristics.
/// Order matters — the first matching rule wins, so more specific rules
/// (e.g. "swiggy instamart" before "swiggy") must come first.
struct MerchantCategorizer {
    static let keywordRules: [(keyword: String, category: ExpenseCategory)] = [
        ("swiggy instamart", .groceries),
        ("instamart", .groceries),
        ("blinkit", .groceries),
        ("zepto", .groceries),
        ("bigbasket", .groceries),
        ("big basket", .groceries),
        ("amazon fresh", .groceries),
        ("d mart", .groceries),
        ("dmart", .groceries),
        ("reliance fresh", .groceries),
        ("more retail", .groceries),
        ("super market", .groceries),
        ("supermarket", .groceries),
        ("swiggy", .food),
        ("zomato", .food),
        ("domino", .food),
        ("pizza hut", .food),
        ("mcdonald", .food),
        ("burger king", .food),
        ("kfc", .food),
        ("starbucks", .food),
        ("chaayos", .food),
        ("cafe", .food),
        ("restaurant", .food),
        ("restaurante", .food),
        ("dining", .food),
        ("uber", .travel),
        ("ola", .travel),
        ("rapido", .travel),
        ("irctc", .travel),
        ("redbus", .travel),
        ("red bus", .travel),
        ("indigo", .travel),
        ("air india", .travel),
        ("goair", .travel),
        ("spicejet", .travel),
        ("vistara", .travel),
        ("akasa", .travel),
        ("makemytrip", .travel),
        ("make my trip", .travel),
        ("cleartrip", .travel),
        ("goibibo", .travel),
        ("mmt", .travel),
        ("scaler", .education),
        ("byju", .education),
        ("udemy", .education),
        ("coursera", .education),
        ("unacademy", .education),
        ("vedantu", .education),
        ("upgrad", .education),
        ("udacity", .education),
        ("physics wallah", .education),
        ("great learning", .education),
        ("coding ninjas", .education),
        ("simplilearn", .education),
        ("jio", .bills),
        ("airtel", .bills),
        ("vodafone", .bills),
        ("bsnl", .bills),
        ("vi ", .bills),
        ("electricity", .bills),
        ("water bill", .bills),
        ("broadband", .bills),
        ("wifi", .bills),
        ("recharge", .bills),
        ("postpaid", .bills),
        ("toll", .bills),
        ("netflix", .subscriptions),
        ("spotify", .subscriptions),
        ("amazon prime", .subscriptions),
        ("prime video", .subscriptions),
        ("hotstar", .subscriptions),
        ("disney", .subscriptions),
        ("sony liv", .subscriptions),
        ("zee5", .subscriptions),
        ("youtube premium", .subscriptions),
        ("apple music", .subscriptions),
        ("chatgpt", .subscriptions),
        ("notion", .subscriptions),
        ("icloud+", .subscriptions),
        ("google one", .subscriptions),
        ("apollo", .health),
        ("pharmacy", .health),
        ("medical", .health),
        ("hospital", .health),
        ("clinic", .health),
        ("doctor", .health),
        ("dentist", .health),
        ("1mg", .health),
        ("netmeds", .health),
        ("wellness", .health),
        ("amazon", .shopping),
        ("flipkart", .shopping),
        ("myntra", .shopping),
        ("mynthra", .shopping),
        ("ajio", .shopping),
        ("nykaa", .shopping),
        ("croma", .shopping),
        ("reliance digital", .shopping),
        ("vijay sales", .shopping),
        ("decathlon", .shopping),
        ("nike", .shopping),
        ("adidas", .shopping),
        ("pvr", .entertainment),
        ("inox", .entertainment),
        ("cinemax", .entertainment),
        ("bookmyshow", .entertainment),
        ("book my show", .entertainment),
        ("theatres", .entertainment),
        ("steam", .entertainment),
        ("playstation", .entertainment),
        ("xbox", .entertainment),
        ("epic games", .entertainment),
    ]

    /// Returns the first matching category for a merchant, or nil when unknown.
    static func heuristic(for merchant: String?) -> ExpenseCategory? {
        guard let merchant else { return nil }
        let lower = merchant.lowercased()
        for rule in keywordRules where lower.contains(rule.keyword) {
            return rule.category
        }
        return nil
    }
}
